---
title: "Malurus Project"
author: "Elroy Au"
date: "12/02/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

### ================================== ###
### Data Analysis                      ###
### ================================== ###

### ================================== ###
### Principal Component Analysis       ###
### ================================== ###

```This is the code used to calculate the principal components used for future analyses and the code used to plot a PCA and a biplot from the data``` 

```{r} 

# load libraries 
library(ggplot2)
library(ggrepel)
library(scatterpie)   # for creating scatterpie graphs
library(readxl) 
library(RcppCNPy)     # for reading .npy (NUMPY) files generated in PCAngsd 
library(sf)           # for reading shapefiles 
library(readxl)
library(RColorBrewer)
library(geosphere)    # to create the distance matrix

# load data
genetic.matrix <- npyLoad("genetic.matrix.cov.npy") # this file should contain the genetic covariance matrix of all of the unfiltered individuals, n=133
snp.filtered.genetic.matrix <- npyLoad("genetic.matrix.snp.filtered.cov.npy") # this file should contain the genetic covariance matrix of all the individuals post pca-filtering, n = 119
clim.filtered.genetic.matrix <- npyLoad("genetic.matrix.clim.filtered.cov.npy") # this file should contain the genetic covariance matrix of all of the individuals post-climate, n = 113
metadata <- read_excel("metadata.xlsx") # this file should contain the metadata for all of the sampled specimens post-PCA filtering, n = 119

# analysis
# calculate eigenvalues
eigenvalues <- eigen(clim.filtered.genetic.matrix)$values         
# calculate eigenvectors
eigenvectors <- eigen(clim.filtered.genetic.matrix)$vectors  
# calculate the principal components using a matrix multiplication 
PC <- as.matrix(clim.filtered.genetic.matrix) %*% eigenvectors
# transpose the data in order to get the loading of the variables for each principal component 
PCs <- t(PC)

# take the principal component scores for individuals to create the PCA plot
PC1 <- PC[,1]
PC2 <- PC[,2]
PC3 <- PC[,3]

# transform into a dataframe
# note: principal components copied into metadata for further data analysis
PCA <- data.frame(PC1, PC2, PC3)

# plot PCA [1] collection state, collection date
ggplot(metadata, aes(x=PC1, y=PC2)) + geom_point(aes(shape = Period, color = STATE), position = "jitter", size = 2.5) + scale_shape_manual(values = c(3, 4, 8, 15, 17, 18, 19, 25)) + theme_bw()

# plot PCA [2] collection state, individual missingness
ggplot (metadata, aes(x=PC1, y=PC2)) + geom_point(aes(shape = Period, color = MISSINGNESS), position = "jitter", size = 2.5) + scale_shape_manual(values = c(3, 4, 8, 15, 17, 18, 19, 25)) + scale_color_continuous(high = "black", low = "turquoise2") + theme_bw() 

# plot biplot
# set pch and colour groups (grouped by collection state: NSW, NT, QLD, SA, VIC, WA, NA)
pch.group <- c(rep(21, times=10), rep(22, times=10), rep(23, times=10), rep(24, times=45), rep(3, times=1), rep(25, times=43))
# red = NSW, gold = NT, green = QLD, blue = SA, black = VIC, pink = WA, black X = N.A
col.group <- c(rep("red", times=10), rep("gold", times=10), rep("green", times=10), rep("skyblue2", times=45), rep("black", times=1), rep("violet", times=43))
# plot the individuals in principal component space 
plot(x=metadata$PC1, y=metadata$PC2, xlab="PC1 (3.18%)", ylab="PC2 (1.23%)", xlim=c(-1.0,1.0),ylim=c(-0.6,0.6), pch=pch.group, col="black", bg=col.group, cex=2, las=1, asp=1)
# y axis
abline(v=0, lty=2, col="grey50")
# x axis
abline(h=0, lty=2, col="grey50")
# set the x and y co-ordinates of the variables, which are equivalent to
# the loading scores of the variables (i.e. the individual samples)
# these will form the arrows on the bi-lot and were created by transposing the 
# principal component data made above (check PCs)
l.x <- PCs[,1]
l.y <- PCs[,2]
arrows(x0=0, x1=l.x, y0=0, y1=l.y, col="red", length = 0.1, lwd = 1.5)
# set text labels 
l.pos <- l.y
lo <- which(l.y < 0)
hi <- which(l.y > 0)
l.pos <- replace(l.pos, lo, "1")
l.pos <- replace(l.pos, hi, "3")
text(l.x, l.y, labels=metadata$`SAMPLE ID`, col="red", pos=l.pos)

# plot PCA on a geographic map
australia <- st_read("australia.shp")
# set objects
a <- ggplot() + geom_sf(data = australia, color = "black", fill = "white")
a + geom_point(data=metadata, aes(x=LONGITUDE, y=LATITUDE, color = PC1), size = 2.5) + scale_color_gradient2()
```

### ================================== ###
### ADMIXTURE ANALYSIS                 ###
### ================================== ###

```This is the code used to analyse the admixture proportions in the sample based off a hypothetical number of ancestral populations k```

```{r}

# load new data
populations <- read.table("admix-pop-data.txt", fill = TRUE, header = FALSE) # this file contains the necessary metadata for ordering individuals via their collection state
q2 <- read.table("admix.2.txt", fill = TRUE, header = FALSE) # this file should contain the estimated admixture proportions for all individuals when the number of ancestral populations k = 2 for creating admixture barplots
q3 <- read.table("admix.3.txt", fill = TRUE, header = FALSE) # this file should contain the estimated admixture proportions for all individuals when the number of ancestral populations k = 3 for creating admixture barplots
q4 <- read.table("admix.4.txt", fill = TRUE, header = FALSE) # this file should contain the estimated admixture proportions for all individuals when the number of ancestral populations k = 4 for creating admixture barplots
q5 <- read.table("admix.5.txt", fill = TRUE, header = FALSE) # this file should contain the estimated admixture proportions for all individuals when the number of ancestral populations k = 5 for creating admixture barplots
q6 <- read.table("admix.6.txt", fill = TRUE, header = FALSE) # this file should contain the estimated admixture proportions for all individuals when the number of ancestral populations k = 6 for creating admixture barplots
# order according to population
ord <- order (populations[,2])
# plot admixture proportions 
barplot(t(q6)[,ord],col=brewer.pal(n=6, name="RdBu"), space=0, border=NA, xlab="Individuals", ylab="Admixture Proportions (K=6)")
# add collection state 
text(tapply(1:nrow(populations), populations[ord,2], mean),-0.05, unique(populations[ord,2]),xpd=T)
# add individual lines
abline(v=cumsum(sapply(unique(populations[ord,1]), function(x){sum(populations[ord,1]==x)})), col="white",lwd=0.5)
# plot admixture proportions on a geographic map
Lat <- metadata$LATITUDE
Long <- metadata$LONGITUDE
# K = 2
K1 <- metadata$K2.1
K2 <- metadata$K2.2
k2.admix <- data.frame(Lat,Long,K1,K2)
a + geom_scatterpie(aes(x = Long, y = Lat), data = k2.admix, cols = c("K1", "K2")) + scale_fill_manual(values=c("#F39C12", "#C39BD3", "#82E0AA", "#F7DC6F", "#EC7063", "#85C1E9")) + theme_light()
# K = 3
K1 <- metadata$K3.1
K2 <- metadata$K3.2
K3 <- metadata$K3.3
k3.admix <- data.frame(Lat,Long,K1,K2,K3)
a + geom_scatterpie(aes(x = Long, y = Lat), data = k3.admix, cols = c("K1", "K2", "K3")) + scale_fill_manual(values=c("#F39C12", "#C39BD3", "#82E0AA", "#F7DC6F", "#EC7063", "#85C1E9")) + theme_light()
# K = 4
K1 <- metadata$K4.1
K2 <- metadata$K4.2
K3 <- metadata$K4.3
K4 <- metadata$K4.4
k4.admix <- data.frame(Lat,Long,K1,K2,K3,K4)
a + geom_scatterpie(aes(x = Long, y = Lat), data = k4.admix, cols = c("K1", "K2", "K3", "K4")) + scale_fill_manual(values=c("#F39C12", "#C39BD3", "#82E0AA", "#F7DC6F", "#EC7063", "#85C1E9")) + theme_light()
# K = 5
K1 <- metadata$K5.1
K2 <- metadata$K5.2
K3 <- metadata$K5.3
K4 <- metadata$K5.4
K5 <- metadata$K5.5
k5.admix <- data.frame(Lat,Long,K1,K2,K3,K4,K5)
a + geom_scatterpie(aes(x = Long, y = Lat), data = k5.admix, cols = c("K1", "K2", "K3", "K4", "K5")) + scale_fill_manual(values=c("#F39C12", "#C39BD3", "#82E0AA", "#F7DC6F", "#EC7063", "#85C1E9")) + theme_light()
# K = 6
K1 <- metadata$K1
K2 <- metadata$K2
K3 <- metadata$K3
K4 <- metadata$K4
K5 <- metadata$K5
K6 <- metadata$K6
k6.admix <- data.frame(Lat,Long,K1,K2,K3,K4,K5,K6)
a + geom_scatterpie(aes(x = Long, y = Lat), data = k6.admix, cols = c("K1", "K2", "K3", "K4", "K5", "K6")) + scale_fill_manual(values=c("#F39C12", "#C39BD3", "#82E0AA", "#F7DC6F", "#EC7063", "#85C1E9")) + theme_light()
```

### ================================== ###
### CALCULATING A DISTANCE MATRIX      ###
### ================================== ###

```This is the code used to calculate a pairwise distance matrix between all specimens which will be used in later analyses in order to control for geography```

```{r}
xy <- data.frame(Long, Lat)
xy.matrix <- as.matrix(xy)
# calculate distance matrix using shortest distance between two points in metres 
distance.matrix <- distm(xy.matrix, fun=distGeo)
```


